import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { AuthProvider } from '@/hooks/use-auth';
import { USE_EMULATORS } from '@/lib/firebase';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {USE_EMULATORS && (
          <div className="bg-orange-500 text-white px-4 py-1 text-center text-sm font-semibold fixed bottom-0 left-0 right-0 z-50">
            🔧 EMULATOR MODE - Connected to Firebase Emulators
          </div>
        )}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
